// Generated by CoffeeScript 1.8.0
(function() {
  var ctx;

  window.applicationContext = {
    consoleText: null,
    consoleHolder: null,
    content: null,
    canvas: null,
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    gl: null,
    crashed: false,
    gameVisible: true
  };

  ctx = window.applicationContext;

  requirejs.config({
    baseUrl: 'js/src',
    paths: {
      dom: 'dom',
      util: 'util',
      wad: 'wad'
    }
  });

  require(['dom/element', 'util/console', 'util/String', 'wad/wadbytedata', 'wad/wad', 'wad/wadloader'], function(element) {
    var callback, startup;
    startup = function() {
      ctx.consoleText = document.querySelector('#consoleText');
      ctx.consoleHolder = document.querySelector('#consoleHolder');
      ctx.content = document.querySelector('#content');
      ctx.printToConsole('Read colormap');
      return ctx.loadFile(callback);
    };
    callback = function() {
      var arrayBuffer, c, color, i, wad, _i, _j, _len, _len1, _ref, _results;
      arrayBuffer = this.response;
      if (arrayBuffer) {
        wad = new ctx.Wad;
        wad.read(arrayBuffer);
        wad.readColormap();
        i = 0;
        _ref = wad.colormap.colors;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          color = _ref[_i];
          ctx.content.appendHtml("<div class='palette' id='palette-" + i + "'></div>");
          for (_j = 0, _len1 = color.length; _j < _len1; _j++) {
            c = color[_j];
            document.querySelector('#palette-' + i).appendHtml("<span class='color' style='background-color: rgb(" + c + "," + c + "," + c + ")'></span>");
          }
          _results.push(i++);
        }
        return _results;
      }
    };
    return startup();
  });

}).call(this);

//# sourceMappingURL=colormap.js.map
