// Generated by CoffeeScript 1.8.0
(function() {
  var ctx;

  window.applicationContext = {
    consoleText: null,
    consoleHolder: null,
    content: null,
    canvas: null,
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    gl: null,
    crashed: false,
    gameVisible: true
  };

  ctx = window.applicationContext;

  requirejs.config({
    baseUrl: '../js/src',
    paths: {
      dom: 'dom',
      util: 'util',
      wad: 'wad'
    }
  });

  require(['dom/element', 'util/console', 'util/String', 'wad/wadbytedata', 'wad/wad', 'wad/wadloader'], function(element) {
    var callback, startup;
    startup = function() {
      ctx.consoleText = document.querySelector('#consoleText');
      ctx.consoleHolder = document.querySelector('#consoleHolder');
      ctx.content = document.querySelector('#content');
      ctx.printToConsole('Read playpal');
      return ctx.loadFile('../resources/doom.wad', callback);
    };
    callback = function() {
      var arrayBuffer, color, i, palette, span, wad, _i, _j, _len, _ref, _results;
      arrayBuffer = this.response;
      if (arrayBuffer) {
        wad = new ctx.Wad;
        wad.read(arrayBuffer);
        wad.readPlaypal();
        i = 0;
        _ref = wad.playpal.palettes;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          palette = _ref[_i];
          ctx.content.appendHtml("<div class='palette' id='palette-" + i + "'></div>");
          for (color = _j = 0; _j <= 255; color = _j += 1) {
            span = "<span class='color' style='background-color: rgb(" + palette.r[color] + "," + palette.g[color] + "," + palette.b[color] + ")'></span>";
            document.querySelector('#palette-' + i).appendHtml(span);
          }
          _results.push(i++);
        }
        return _results;
      }
    };
    return startup();
  });

}).call(this);

//# sourceMappingURL=playpal.js.map
