// Generated by CoffeeScript 1.8.0
(function() {
  var ctx;

  window.applicationContext = {
    consoleText: null,
    consoleHolder: null,
    content: null,
    canvas: null,
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    gl: null,
    crashed: false,
    gameVisible: true
  };

  ctx = window.applicationContext;

  requirejs.config({
    baseUrl: '../js/src',
    paths: {
      dom: 'dom',
      util: 'util',
      wad: 'wad'
    }
  });

  require(['dom/element', 'util/console', 'util/String', 'wad/wadbytedata', 'wad/wad', 'wad/wadloader'], function(element) {
    var callback, startup;
    startup = function() {
      ctx.consoleText = document.querySelector('#consoleText');
      ctx.consoleHolder = document.querySelector('#consoleHolder');
      ctx.content = document.querySelector('#content');
      ctx.printToConsole('Read texture');
      return ctx.loadFile('../resources/doom.wad', callback);
    };
    callback = function() {
      var arrayBuffer, li, name, texture, wad, _ref, _results;
      arrayBuffer = this.response;
      if (arrayBuffer) {
        wad = new ctx.Wad;
        wad.read(arrayBuffer);
        wad.readTextures();
        ctx.content.appendHtml("<ul id='textures'></ul>");
        _ref = wad.textures;
        _results = [];
        for (name in _ref) {
          texture = _ref[name];
          li = "<li><a href='#'>" + name + "</a></li>";
          _results.push(document.querySelector('#textures').appendHtml(li));
        }
        return _results;
      }
    };
    return startup();
  });

}).call(this);

//# sourceMappingURL=texture.js.map
