// Generated by CoffeeScript 1.8.0
(function() {
  Element.prototype.appendHtml = function(html) {
    return this.innerHTML = this.innerHTML + html;
  };

}).call(this);

//# sourceMappingURL=element.js.map
