// Generated by CoffeeScript 1.8.0
(function() {
  var LumpInfo, ctx;

  ctx = window.applicationContext;

  ctx.Wad = (function() {
    var DIRECTORY_LUMP_ENTRY_SIZE, LUMP_NAMES;

    DIRECTORY_LUMP_ENTRY_SIZE = 16;

    LUMP_NAMES = ["BLOCKMAP", "COLORMAP", "DMXGUS", "ENDOOM", "GENMIDI", "LINEDEFS", "NODES", "PLAYPAL", "PNAMES", "REJECT", "SECTORS", "SEGS", "SIDEDEFS", "SSECTORS", "TEXTURE1", "TEXTURE2", "THINGS", "VERTEXES"];

    function Wad() {
      this.header = {};
      this.lumpHash = {};
      this.data = null;
    }

    Wad.prototype.read = function(data) {
      this.data = new ctx.WadByteData(data);
      return this.readHeader();
    };

    Wad.prototype.readHeader = function() {
      this.header.identification = this.data.getString(0, 4);
      if (this.header.identification !== 'IWAD') {
        throw 'This not a IWAD format';
      }
      this.header.numberLumps = this.data.getUInt32(0x04);
      this.header.lumpInfoTableOffset = this.data.getUInt32(0x08);
      if (this.header.lumpInfoTableOffset + this.header.numberLumps * DIRECTORY_LUMP_ENTRY_SIZE > this.data.lengthInBytes) {
        throw "Can't contains all lump table";
      }
      return this.collectLumpInfo();
    };

    Wad.prototype.collectLumpInfo = function() {
      var i, lumpInfo, name, offset, position, size, _i, _ref, _results;
      console.log('fdp');
      _results = [];
      for (i = _i = 0, _ref = this.header.numberLumps; _i <= _ref; i = _i += 1) {
        offset = this.header.lumpInfoTableOffset + i * DIRECTORY_LUMP_ENTRY_SIZE;
        position = this.data.getUInt32(offset + 0x00);
        size = this.data.getUInt32(offset + 0x04);
        name = this.data.getString(offset + 0x08, 8);
        lumpInfo = new LumpInfo(name, position, size);
        _results.push(this.lumpHash[name] = lumpInfo);
      }
      return _results;
    };

    return Wad;

  })();

  LumpInfo = (function() {
    function LumpInfo(name, position, size) {
      this.name = name;
      this.position = position;
      this.size = size;
    }

    return LumpInfo;

  })();

}).call(this);

//# sourceMappingURL=wad.js.map
