// Generated by CoffeeScript 1.8.0
(function() {
  var ctx;

  ctx = window.applicationContext;

  ctx.Wad = (function() {
    Wad.lumpNames = ["THINGS", "LINEDEFS", "SIDEDEFS", "VERTEXES", "SEGS", "SSECTORS", "NODES", "SECTORS", "REJECT", "BLOCKMAP", "GENMIDI", "DMXGUS", "PLAYPAL", "COLORMAP", "ENDOOM", "TEXTURE1", "TEXTURE2", "PNAMES"];

    function Wad() {
      this.header = {};
    }

    Wad.prototype.read = function(data) {
      this.data = new ctx.WadByteData(data);
      return this.readHeader();
    };

    Wad.prototype.readHeader = function() {
      this.header.identification = this.data.getString(0, 4);
      ctx.printToConsole(this.header.identification);
      this.header.numberLumps = this.data.getUInt32(0x04);
      ctx.printToConsole(this.header.numberLumps);
      return ctx.printToConsole(this.data.offsetInBytes);
    };

    return Wad;

  })();

}).call(this);

//# sourceMappingURL=wad.js.map
