// Generated by CoffeeScript 1.8.0
(function() {
  var ctx;

  ctx = window.applicationContext;

  ctx.printToConsole = function(text) {
    ctx.consoleText.appendHtml("\r" + text);
    return ctx.consoleHolder.scrollTop = ctx.consoleHolder.scrollHeight;
  };

  ctx.printToConsoleNoNewLine = function(text) {
    ctx.consoleText.appendHtml(" " + text);
    return ctx.consoleHolder.scrollTop = ctx.consoleHolder.scrollHeight;
  };

}).call(this);

//# sourceMappingURL=console.js.map
