// Generated by CoffeeScript 1.8.0
(function() {
  String.fromCharCodes = function(array) {
    var code, str, _i, _len;
    str = '';
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      code = array[_i];
      str += String.fromCharCode(code);
    }
    return str;
  };

}).call(this);

//# sourceMappingURL=string.js.map
